version: '3.4'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  db:
    image: postgres
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=mydbname
    volumes:
      - ./postgres/volumes/data/db:/var/lib/postgresql/data
    ports:
       - "5432:5432"